name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
      branches:
        - master

jobs:
    code-style-and-static-analysis:
        runs-on: ubuntu-18.04
        steps:
            - name: Setup PHP 7.4
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  extensions: json, libxml, pdo, pdo_mysql, pdo_sqlite, pdo_pgsql, sqlite3
                  coverage: pcov

            - uses: actions/checkout@v1
              with:
                  fetch-depth: 1

            - name: Composer get cache directory
              id: composer-cache
              run: |
                  echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Composer cache
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - name: Composer validate
              run: composer validate

            - name: Composer install
              run: composer install --prefer-dist --no-interaction

            - name: Code Style
              run: composer cs-check

            - name: PHPStan
              run: composer stan

            - name: Psalm
              run: composer psalm

    integration:
        runs-on: ubuntu-18.04
        steps:
            - name: Setup PHP 7.4
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  extensions: json, libxml, pdo, pdo_mysql, pdo_sqlite, pdo_pgsql, sqlite3
                  coverage: pcov

            - uses: actions/checkout@v2

            - name: Composer get cache directory
              id: composer-cache
              run: |
                  echo "::set-output name=dir::$(composer config cache-files-dir)"

            - name: Composer cache
              uses: actions/cache@v2
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-composer-

            - name: Install integration demo shop
              run: git clone https://github.com/spryker-shop/suite.git

            - name: Setup
              run: cd suite && composer install

            - name: Generate transfer objects
              run: cd suite && APPLICATION_ENV=development vendor/bin/console transfer:generate

            - name: Generate transfer databuilder objects
              run: cd suite && APPLICATION_ENV=development vendor/bin/console transfer:databuilder:generate

            - name: Propel install
              run: |
                  cd suite
                  APPLICATION_ENV=development vendor/bin/console propel:schema:copy
                  APPLICATION_ENV=development vendor/bin/console propel:model:build
                  APPLICATION_ENV=development vendor/bin/console transfer:entity:generate
